version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: application
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - db
    ports:
      - 8888:8080
#    networks:
#      - spring-boot-mysql-network

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
#    networks:
#      - spring-boot-mysql-network
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: password
#      MYSQL_IP: 0.0.0.0
      MYSQL_DATABASE: mysql    
 
#networks:
#  spring-boot-mysql-network:
#    driver: bridge

