version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: application
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql
    ports:
      - 8080:8888

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
#    environment:
      
    networks:
      - spring-boot-mysql-network
    volumes:
      - .
 
volumes:
  mydata:

networks:
  spring-boot-mysql-network:
    driver: bridge

secrets:
  external:
    external: true
  secret_file:
    file: secrets