version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: application
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - .
    command: 

volumes:
  mydata: