version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: application
    volumes:
      - mydata:/target/

  db:
    image: mysql
    container_name: mysql
    ports:
      - 8888:8080
    volumes:
      - .
    command: /opt/tomcat/bin/catalina.sh run

volumes:
  mydata: