version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: application
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - db
    ports:
      - 8888:8080

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: password
      MYSQL_IP: 172.25.0.2
      MYSQL_DATABASE: mysql    
 
#    volumes:
#      - mydata:/var/lib/mysql
 
#volumes:
#  mydata:

